// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKv8NQ53OepO4UrfxyNQ5RMjd72HM4NVY',
    appId: '1:922697138135:web:cbc9bb30a6a38fe4bf9592',
    messagingSenderId: '922697138135',
    projectId: 'rapidd-technologies-demo',
    authDomain: 'rapidd-technologies-demo.firebaseapp.com',
    storageBucket: 'rapidd-technologies-demo.firebasestorage.app',
    measurementId: 'G-S0Q37P5N8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBYrDRaED5u2K4sphsa8Zqx3MBEhuxTlg',
    appId: '1:922697138135:android:bb7cbd2822ae6f54bf9592',
    messagingSenderId: '922697138135',
    projectId: 'rapidd-technologies-demo',
    storageBucket: 'rapidd-technologies-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaNkqA9WzKkIKHyp0bYRjtCHrfIoArIXE',
    appId: '1:922697138135:ios:4d523a93d6ae94e8bf9592',
    messagingSenderId: '922697138135',
    projectId: 'rapidd-technologies-demo',
    storageBucket: 'rapidd-technologies-demo.firebasestorage.app',
    iosBundleId: 'com.example.rapiddTechnologiesDemo',
  );
}
